### ISSUE TITLE
Navbar should be template-able or a Vue component

### ISSUE THREAD

**Issue by HugoKlepsch** [HugoKlepsch/inventoryBackend#30]
The problem can be seen on the login and sign up page: 
Both the login and sign up page are based on the "logged out" base navbar. On the login page there is a link in the nav bar to the sign up page. On the sign up page there is also a link to the sign up page, even though you're already there!

The navbar is not as simple as "logged in"/"logged out", it is context dependent. 

This issue tracks brainstorming and implementation of a configurable navbar. When rendering the login page, the python code should be able to say "add a navbar action: {'name': 'Sign up', 'link': '/signup.html'}"

**Comment by HugoKlepsch** [comment]
This could be implemented using Jinja, or making a navbar Vue module.

**Comment by nskoretz** [comment]
This issue was done during the creation of the Vue Login page.
