### ISSUE TITLE
Revisit theme, and use gradients with bright colors

### ISSUE THREAD

**Issue by HugoKlepsch** [HugoKlepsch/inventoryBackend#55]
https://www.w3schools.com/css/css3_gradients.asp
Specifically, the navbar should have some sort of gradient. Maybe a less harsh gradient as the background color. 
Turqoise - Purle
Red Blue
Green Turqoise
Find a good pair you like!

**Comment by nskoretz** [comment]
Interesting. I didn't think you'd move away from "dark mode".

**Comment by nskoretz** [comment]
Gradient navbar should be doable, do you want a gradient background to the pages?
