### ISSUE TITLE
Consider using marshmallow as a serialization library

### ISSUE THREAD

**Issue by HugoKlepsch** [HugoKlepsch/inventoryBackend#64]
Right now we don't have any form of runtime validation of data other than ad-hoc checking of fields. 

I use marshmallow at work, and it buys us data validation (input and output), automatic serialization, and automatic object construction on de-serialization.

**Comment by nskoretz** [comment]
This seems like a great addition to the server side. I believe we can also get tighter with our Typescript type checking for information that is being posted to the API, which should help validate things from the client-side.
